//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleaner
    {
        public Cleaner()
        {
            this.Cleaner_Task = new HashSet<Cleaner_Task>();
        }
    
        public string cleaner_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string gender { get; set; }
    
        public virtual ICollection<Cleaner_Task> Cleaner_Task { get; set; }
    }
}
