//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Cleaner_Task = new HashSet<Cleaner_Task>();
            this.Task_Room = new HashSet<Task_Room>();
        }
    
        public string room_id { get; set; }
        public string status { get; set; }
        public string category_id { get; set; }
        public string floor_id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Cleaner_Task> Cleaner_Task { get; set; }
        public virtual Floor Floor { get; set; }
        public virtual ICollection<Task_Room> Task_Room { get; set; }
    }
}
