//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Room
    {
        public string room_id { get; set; }
        public string task_id { get; set; }
        public string cleaned { get; set; }
        public string @checked { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Task Task { get; set; }
    }
}
