//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleaner_Category
    {
        public Cleaner_Category()
        {
            this.Cleaners = new HashSet<Cleaner>();
        }
    
        public string cleaner_category_id { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Cleaner> Cleaners { get; set; }
    }
}
