//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Floor
    {
        public Floor()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public string floor_id { get; set; }
        public string description { get; set; }
        public string manager_id { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
