//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public Manager()
        {
            this.Floors = new HashSet<Floor>();
            this.Tasks = new HashSet<Task>();
        }
    
        public string manager_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string gender { get; set; }
    
        public virtual ICollection<Floor> Floors { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
