//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HKAppEntities : DbContext
    {
        public HKAppEntities()
            : base("name=HKAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<Cleaner> Cleaners { get; set; }
        public DbSet<Cleaner_Category> Cleaner_Category { get; set; }
        public DbSet<Cleaner_Task> Cleaner_Task { get; set; }
        public DbSet<Floor> Floors { get; set; }
        public DbSet<Manager> Managers { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<Task_Category> Task_Category { get; set; }
        public DbSet<Task_Room> Task_Room { get; set; }
    }
}
