//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Cleaner_Task = new HashSet<Cleaner_Task>();
            this.Task_Room = new HashSet<Task_Room>();
            this.Managers = new HashSet<Manager>();
        }
    
        public string task_id { get; set; }
        public string task_description { get; set; }
    
        public virtual ICollection<Cleaner_Task> Cleaner_Task { get; set; }
        public virtual ICollection<Task_Room> Task_Room { get; set; }
        public virtual ICollection<Manager> Managers { get; set; }
    }
}
